# Casting in Python is therefore done using constructor functions: 
# int()
x = int(1)
print(x, "=", type(x)) 
y = int(2.8)
print(y, "=", type(y)) 
z = int("3")
print(z, "=", type(z))

# float()
x = float(1)
print(x, "=", type(x)) 
y = float(2.8)
print(y, "=", type(y)) 
z = float("3")
print(z, "=", type(z))
w = float("4.2")
print(w, "=", type(w))


# str()
x = str("s1")
print(x, "=", type(x)) 
y = str(2)
print(y, "=", type(y)) 
z = str(3.0)
print(z, "=", type(z))